/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.CandidatoDAO;
import DAO.VagaDAO;
import DTO.Candidato;
import DTO.Candidato_Vaga;
import DTO.Vaga;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe Bispo
 */
public class AvaliaCandidato extends javax.swing.JFrame {

    /**
     * Creates new form AvaliaCandidato
     */
    public AvaliaCandidato() {
        initComponents();
        listarVagas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblvaga = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtnome = new javax.swing.JLabel();
        txtdatanascimento = new javax.swing.JLabel();
        txtcpf = new javax.swing.JLabel();
        txtendereco = new javax.swing.JLabel();
        txtpretensaosalarial = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtformacao = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtexperiencia = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();

        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("CANDIDATO");

        jLabel3.setText("VAGA CANDIDATADA");

        jLabel4.setText("Nome:");

        jLabel5.setText("Idade:");

        jLabel6.setText("CPF:");

        jLabel7.setText("Endereco:");

        jLabel8.setText("Pretensao salarial:");

        jLabel9.setText("Formacao:");

        jLabel10.setText("Experiencia:");

        jLabel11.setText("Cargo:");

        jLabel12.setText("Descrição:");

        jLabel13.setText("jLabel13");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Pretensão salarial:");

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(jTextArea1);

        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/design-avaliacao.png"))); // NOI18N
        jLabel24.setText("a");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblvaga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CPF", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblvaga);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 390, 470));

        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 670, 240, 70));

        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 530, 490, -1));

        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, 230, 70));

        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 670, 240, 70));

        jLabel25.setText("CANDIDATO");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 90, -1));

        jLabel27.setText("Nome:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, 20));

        jLabel28.setText("Idade:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, 20));

        jLabel29.setText("CPF:");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, 20));

        jLabel30.setText("Endereço:");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, 20));

        jLabel31.setText("Pretensão Salarial:");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, 20));

        jLabel32.setText("Formação:");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        jLabel33.setText("Experiência:");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, -1, -1));

        txtnome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 460, 20));

        txtdatanascimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtdatanascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 460, 20));

        txtcpf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 460, 20));

        txtendereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 460, 20));

        txtpretensaosalarial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtpretensaosalarial, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 460, 20));

        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 590, -1));

        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 240, 70));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 640, -1, -1));

        txtformacao.setColumns(20);
        txtformacao.setRows(5);
        jScrollPane3.setViewportView(txtformacao);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 460, -1));

        txtexperiencia.setColumns(20);
        txtexperiencia.setRows(5);
        jScrollPane4.setViewportView(txtexperiencia);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 460, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/design-avaliacao.png"))); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String motivo;
        int setar = tblvaga.getSelectedRow();
        String cpf = tblvaga.getModel().getValueAt(setar, 0).toString();
        VagaDAO vagadao = new VagaDAO();        
        
        motivo = JOptionPane.showInputDialog("INSIRA O MOTIVO DA REPROVAÇÃO: ");
        Candidato_Vaga objcandidatovaga = new Candidato_Vaga();
        objcandidatovaga.setCpf(cpf);
        objcandidatovaga.setMotivo(motivo);
        vagadao.reprovacandidato(objcandidatovaga);
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        int setar = tblvaga.getSelectedRow();
        String cpf = tblvaga.getModel().getValueAt(setar, 0).toString();
        Candidato objcandidato = new Candidato();
        objcandidato.setCPF(cpf);
        VagaDAO vagadao = new VagaDAO();        
        
        vagadao.aprovacandidato(objcandidato);
        
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        try{
            int setar = tblvaga.getSelectedRow();
            String cpf = tblvaga.getModel().getValueAt(setar, 0).toString();
            Candidato objcandidato = new Candidato();
            objcandidato.setCPF(cpf);
            VagaDAO vagadao = new VagaDAO();
            CandidatoDAO candidatodao = new CandidatoDAO();

            ResultSet rs = vagadao.analisecandidato(objcandidato);
            ResultSet rs2 = candidatodao.mostrarexperienciaprofissional(objcandidato);
            ResultSet rs3 = candidatodao.mostrarformacaoacademica(objcandidato);

            if(rs.next()){
                txtnome.setText(rs.getString("nome_completo"));
                txtdatanascimento.setText(rs.getString("data_nascimento"));
                txtcpf.setText(rs.getString("cpf"));
                txtpretensaosalarial.setText(String.valueOf(rs.getDouble("pretencao_salarial")));
                txtendereco.setText(rs.getString("endereco"));

            }
            if(rs2.next()){
                txtexperiencia.setText(rs2.getString("descricao"));
            }
            if(rs3.next()){
                txtformacao.setText(rs3.getString("descricao"));
            }

        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "botao detalhes" + e);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvaliaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvaliaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvaliaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvaliaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvaliaCandidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblvaga;
    private javax.swing.JLabel txtcpf;
    private javax.swing.JLabel txtdatanascimento;
    private javax.swing.JLabel txtendereco;
    private javax.swing.JTextArea txtexperiencia;
    private javax.swing.JTextArea txtformacao;
    private javax.swing.JLabel txtnome;
    private javax.swing.JLabel txtpretensaosalarial;
    // End of variables declaration//GEN-END:variables

    
    private void listarVagas(){
    try{
        VagaDAO vagadao = new VagaDAO();
        DefaultTableModel model = (DefaultTableModel) tblvaga.getModel();
        model.setNumRows(0);
        String Id_vaga;
        Id_vaga = JOptionPane.showInputDialog("DIGITE O NOME DO ID DA VAGA: ");
        int Id_temp;
        Id_temp = Integer.parseInt(Id_vaga);
        Vaga objvaga = new Vaga();
        objvaga.setId_vaga(Id_temp);
        ArrayList<Candidato_Vaga> lista = vagadao.AvaliaCandidato(objvaga);
        
        for (int num = 0; num < lista.size(); num++){
            model.addRow(new Object[]{
               
                lista.get(num).getCpf(), 
                lista.get(num).getStatus()
            });
        }
        
    } catch(Exception erro){
        JOptionPane.showMessageDialog(null, "Listar Vagas" + erro);
    }
}

}


