/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.CandidatoDAO;
import DTO.Candidato;
import DTO.Experiencia_Academica;
import DTO.Experiencia_Profissional;
import javax.swing.JOptionPane;
import DTO.ValidaCPF;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;

/**
 *
 * @author Lucas Emanoel
 */
public class CadastroCandidato extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCandidato
     */
    
    public CadastroCandidato() {
        initComponents();
        pdfanexa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pdfanexa = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtsalario = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        txtdata = new javax.swing.JFormattedTextField();
        txtcpf = new javax.swing.JFormattedTextField();
        txtsenha = new javax.swing.JPasswordField();
        txtconfirma = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtacademica = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtprofissional = new javax.swing.JTextArea();
        txtsemprofissional = new javax.swing.JRadioButton();
        txtsemacademica = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pdfanexa.setAccessory(jButton1);
        pdfanexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfanexaActionPerformed(evt);
            }
        });
        getContentPane().add(pdfanexa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Anexar PDF");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 240, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 84, 22));
        jLabel2.setText("Cargo de Interesse:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 84, 22));
        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(243, 84, 22));
        jLabel4.setText("Nome Completo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(243, 84, 22));
        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(243, 84, 22));
        jLabel6.setText("Telefone:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(243, 84, 22));
        jLabel7.setText("Endereço:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(243, 84, 22));
        jLabel8.setText("Data de Nascimento:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(243, 84, 22));
        jLabel9.setText("Confirme Senha:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(243, 84, 22));
        jLabel10.setText("Pretensão Salarial:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(243, 84, 22));
        jLabel11.setText("Senha:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(243, 84, 22));
        jLabel12.setText("Formação Acadêmica:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));
        getContentPane().add(txtsalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 400, 30));
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 400, 30));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 400, 30));
        getContentPane().add(txtendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 400, 30));
        getContentPane().add(txttelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 400, 30));

        try {
            txtdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 400, 30));

        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 400, 30));
        getContentPane().add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 400, 30));
        getContentPane().add(txtconfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 400, 30));

        txtacademica.setColumns(20);
        txtacademica.setRows(5);
        jScrollPane1.setViewportView(txtacademica);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 350, -1));

        txtprofissional.setColumns(20);
        txtprofissional.setRows(5);
        jScrollPane2.setViewportView(txtprofissional);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 350, -1));

        txtsemprofissional.setText("Não Possuo");
        txtsemprofissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsemprofissionalActionPerformed(evt);
            }
        });
        getContentPane().add(txtsemprofissional, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        txtsemacademica.setText("Não Possuo");
        txtsemacademica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsemacademicaActionPerformed(evt);
            }
        });
        getContentPane().add(txtsemacademica, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(243, 84, 22));
        jLabel13.setText("Experiência Profissional:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco de Dados", "Full Stack", "BackEnd", "FrontEnd", "Machine Learning", "Programação Python" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 120, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco de Dados", "Full Stack", "BackEnd", "FrontEnd", "Machine Learning", "Programação Python" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 120, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco de Dados", "Full Stack", "BackEnd", "FrontEnd", "Machine Learning", "Programação Python" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 130, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Anexar PDF");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 240, 40));

        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 160, 40));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Arquivo não selecionado");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 290, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/candidato-cadastro2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -60, -1, 700));

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Login");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sobre");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pdfanexa.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsemacademicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsemacademicaActionPerformed

        if (txtsemacademica.isSelected()) {
            txtacademica.setVisible(false);
        } else {
            txtacademica.setVisible(true);
        }
    }//GEN-LAST:event_txtsemacademicaActionPerformed

    private void txtsemprofissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsemprofissionalActionPerformed
        if (txtsemprofissional.isSelected()) {
            txtprofissional.setVisible(false);
        } else {
            txtprofissional.setVisible(true);
        }


    }//GEN-LAST:event_txtsemprofissionalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         long telefone;
        double salario;
        String nome, data, email, CPF, endereco, senha, confirma, formacaoAcademica, formacaoProfissional, naopossuiAcd, naopossuiProf, CPFV;

        Candidato objcandidato = new Candidato();
        Experiencia_Academica objexacd = new Experiencia_Academica();
        Experiencia_Profissional objexprof = new Experiencia_Profissional();

        
        CPF = txtcpf.getText();
        CPFV = CPF.replaceAll("[^0-9]", "");
        nome = txtnome.getText();
        data = txtdata.getText();
        email = txtemail.getText();
        endereco = txtendereco.getText();
        telefone = Long.parseLong(txttelefone.getText());
        salario = Double.parseDouble(txtsalario.getText());
        senha = txtsenha.getText();
        confirma = txtconfirma.getText();
        formacaoAcademica = txtacademica.getText();
        formacaoProfissional = txtprofissional.getText();

        objcandidato.setCPF(CPF);
        objcandidato.setNome_Completo(nome);
        objcandidato.setData_Nascimento(data);
        objcandidato.setEmail(email);
        objcandidato.setEndereco(endereco);
        objcandidato.setTelefone(telefone);
        objcandidato.setSalario(salario);
        objcandidato.setSenha(senha);

        if (txtsemacademica.isSelected() && txtsemprofissional.isSelected()) {
            objexprof.setDescricao("Nao possui experiencia profissional");
            objexacd.setDescricao("Nao possui formacao academica");

        } else if (txtsemprofissional.isSelected()) {
            objexprof.setDescricao("Nao possui experiencia profissional");

        } else if (txtsemacademica.isSelected()) {
            objexacd.setDescricao("Nao possui experiencia academica");

        } else {
            objexacd.setDescricao(formacaoAcademica);
            objexprof.setDescricao(formacaoProfissional);
        }

        CandidatoDAO objcandidatodao = new CandidatoDAO();

        if (ValidaCPF.isCPF(CPFV) == true) {

            if (senha.equals(confirma)) {

                objcandidatodao.cadastrarCandidato(objcandidato);
                objcandidatodao.cadastrarexperiencias(objexacd, objcandidato, objexprof);
                this.setVisible(false);
                new LoginCandidato().setVisible(true);

            } else {

                JOptionPane.showMessageDialog(null, "As senhas não são as mesmas");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "CPF Inválido");
        }
     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pdfanexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfanexaActionPerformed
        // TODO add your handling code here
        String apdf = "";
        File f = new  File(apdf);
        
        jLabel14.setText(pdfanexa.getSelectedFile().getAbsolutePath());
        apdf = jLabel14.getText();
        pdfanexa.setVisible(false);
    }//GEN-LAST:event_pdfanexaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCandidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFileChooser pdfanexa;
    private javax.swing.JTextArea txtacademica;
    private javax.swing.JPasswordField txtconfirma;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JFormattedTextField txtdata;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextArea txtprofissional;
    private javax.swing.JTextField txtsalario;
    private javax.swing.JRadioButton txtsemacademica;
    private javax.swing.JRadioButton txtsemprofissional;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
