/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.VagaDAO;
import DTO.Vaga;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas Emanoel
 */
public class TabelaVagas extends javax.swing.JFrame {

    /**
     * Creates new form TabelaVagas
     */
    public TabelaVagas() {
        initComponents();
        listarVagas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblvaga = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtVaga = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        txtPrenSal = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtExp = new javax.swing.JTextField();
        AltVaga = new javax.swing.JButton();
        jbtnExcluir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblvaga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome da Vaga", "Descrição", "Pretensão Salarial", "Cargo", "Experiencia Necessária"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblvaga.setFocusable(false);
        tblvaga.setRowHeight(25);
        tblvaga.setSelectionBackground(new java.awt.Color(255, 181, 108));
        tblvaga.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblvaga);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 870, 280));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Atualizar Tabela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 250, 150, 40));

        txtID.setText("ID ");
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, 150, 30));

        txtVaga.setText("Nome da Vaga");
        getContentPane().add(txtVaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 150, 30));

        txtDesc.setText("Descrição");
        getContentPane().add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 460, 150, 30));

        txtPrenSal.setText("Pretensão Salarial");
        getContentPane().add(txtPrenSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, 150, 30));

        txtCargo.setText("Cargo");
        getContentPane().add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 540, 150, 30));

        txtExp.setText("Experiencia Necessária");
        getContentPane().add(txtExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 580, 150, 30));

        AltVaga.setText("Alterar Vaga");
        AltVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltVagaActionPerformed(evt);
            }
        });
        getContentPane().add(AltVaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 660, 150, 40));

        jbtnExcluir.setText("Excluir");
        jbtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 660, 130, 40));

        jButton2.setText("Carregar Campos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 610, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vagas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1350, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listarVagas();
        JOptionPane.showMessageDialog(null, "A tabela foi atualizada !");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void AltVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltVagaActionPerformed
        // TODO add your handling code here:
        alterarVaga();
        listarVagas();
        JOptionPane.showMessageDialog(null, "A vaga foi alterada !");

    }//GEN-LAST:event_AltVagaActionPerformed

    private void jbtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcluirActionPerformed
        // TODO add your handling code here:
        ExcluirVaga();
        listarVagas();
        

    }//GEN-LAST:event_jbtnExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int setar = tblvaga.getSelectedRow();
        
        txtID.setText(tblvaga.getModel().getValueAt(setar, 0).toString());
        txtVaga.setText(tblvaga.getModel().getValueAt(setar, 1).toString());
        txtDesc.setText(tblvaga.getModel().getValueAt(setar, 2).toString());
        txtPrenSal.setText(tblvaga.getModel().getValueAt(setar, 3).toString());
        txtCargo.setText(tblvaga.getModel().getValueAt(setar, 4).toString());
        txtExp.setText(tblvaga.getModel().getValueAt(setar, 5).toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaVagas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AltVaga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JTable tblvaga;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtExp;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPrenSal;
    private javax.swing.JTextField txtVaga;
    // End of variables declaration//GEN-END:variables

private void listarVagas(){
    try{
        VagaDAO objvagadao = new VagaDAO();
        DefaultTableModel model = (DefaultTableModel) tblvaga.getModel();
        model.setNumRows(0);
        
        ArrayList<Vaga> lista = objvagadao.PesquisarVagas();
        
        for (int num = 0; num < lista.size(); num++){
            model.addRow(new Object[]{
               
                lista.get(num).getId_vaga(),
                lista.get(num).getNome(),
                lista.get(num).getDescricao(),
                lista.get(num).getSalario(),
                lista.get(num).getCargo(),
                lista.get(num).getExpe_prof()
            });
        }
        
    } catch(Exception erro){
        JOptionPane.showMessageDialog(null, "Listar Vagas" + erro);
    }
}

private void alterarVaga(){
    int id_vaga;
    double Salario;
    String Nome, Descricao, Cargo, Expe_prof;
    
    id_vaga = Integer.parseInt(txtID.getText());
    Salario = Integer.parseInt(txtPrenSal.getText());
    Nome = txtVaga.getText();
    Descricao = txtDesc.getText();
    Cargo = txtCargo.getText();
    Expe_prof = txtExp.getText();
    
    Vaga objvaga = new Vaga();
    
    objvaga.setId_vaga(id_vaga);
    objvaga.setDescricao(Descricao);
    objvaga.setSalario(Salario);
    objvaga.setNome(Nome);
    objvaga.setCargo(Cargo);
    objvaga.setExpe_prof(Expe_prof);
    
    VagaDAO objvagadao = new VagaDAO();
    objvagadao.alterarVaga(objvaga);
    }

private void ExcluirVaga(){
        int id_vaga;
        
        id_vaga = Integer.parseInt(txtID.getText());
        
        Vaga objvaga = new Vaga();
        objvaga.setId_vaga(id_vaga);
        
        VagaDAO objvagadao = new VagaDAO();
        objvagadao.excluirVaga(objvaga);
    }

    
}
