/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.VagaDAO;
import DTO.Candidato;
import DTO.Vaga;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas Emanoel
 */
public class VagaAberta extends javax.swing.JFrame {

    /**
     * Creates new form VagaAberta
     */
    public VagaAberta() {
        initComponents();
        listarVagas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblvaga = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        experiencia = new javax.swing.JLabel();
        nomevaga = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        salario = new javax.swing.JLabel();
        cargo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblvaga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome da Vaga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblvaga);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 300, 140));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 84, 22));
        jLabel1.setText("Selecione uma das vagas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 84, 22));
        jLabel2.setText("Descrição");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 84, 22));
        jLabel3.setText("Pretensão Salarial");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(243, 84, 22));
        jLabel4.setText("Cargo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(243, 84, 22));
        jLabel5.setText("Experiência Necessaria");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        experiencia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(experiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 400, 80));

        nomevaga.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(nomevaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, 80));

        descricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 190, 70));

        salario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(salario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 150, 40));

        cargo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 180, 70));

        jButton1.setText("Detalhes da Vaga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 220, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(243, 84, 22));
        jLabel7.setText("Nome da Vaga");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Candidatar-se");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 442, 560, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vagaaberta.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, -440, -1, 1040));

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Login");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sobre");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Sair");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
            int setar = tblvaga.getSelectedRow();
        
            String nome = tblvaga.getModel().getValueAt(setar, 1).toString();
            Vaga objvaga = new Vaga(); 
            objvaga.setNome(nome);
            
            VagaDAO objvagadao = new VagaDAO();
            ResultSet rsvagadao = objvagadao.Pesquisa(objvaga);
            
            if (rsvagadao.next()){
            nomevaga.setText(rsvagadao.getString("nome_vaga"));
            descricao.setText(rsvagadao.getString("descricao_vaga"));
            salario.setText(String.valueOf(rsvagadao.getDouble("pretencao_salarial")));
            cargo.setText(rsvagadao.getString("cargo"));
            experiencia.setText(rsvagadao.getString("experiencia_profissional_necessaria"));
            }
            
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Botão" + e);
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        int setar = tblvaga.getSelectedRow();
        
            String id = tblvaga.getModel().getValueAt(setar, 0).toString();
            String nome = tblvaga.getModel().getValueAt(setar, 1).toString();
            
            int id_vaga = Integer.valueOf(id);
            
            Vaga objvaga = new Vaga();
            
            objvaga.setId_vaga(id_vaga);
            objvaga.setNome(nome);
            
            VagaDAO objvagadao = new VagaDAO();
            
            objvagadao.alterarnumeroCandidato(objvaga);
        
            
            
            
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VagaAberta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VagaAberta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VagaAberta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VagaAberta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VagaAberta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cargo;
    private javax.swing.JLabel descricao;
    private javax.swing.JLabel experiencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomevaga;
    private javax.swing.JLabel salario;
    private javax.swing.JTable tblvaga;
    // End of variables declaration//GEN-END:variables


    private void listarVagas(){
    try{
        VagaDAO objvagadao = new VagaDAO();
        DefaultTableModel model = (DefaultTableModel) tblvaga.getModel();
        model.setNumRows(0);
        
        ArrayList<Vaga> lista = objvagadao.PesquisarVagas();
        
        for (int num = 0; num < lista.size(); num++){
            model.addRow(new Object[]{
               
                lista.get(num).getId_vaga(),
                lista.get(num).getNome(),
            });
        }
        
    } catch(Exception erro){
        JOptionPane.showMessageDialog(null, "Listar Vagas" + erro);
    }
}
    private void CarregarCampos(){
       int setar = tblvaga.getSelectedRow();
        
       nomevaga.setText(tblvaga.getModel().getValueAt(setar, 1).toString());
    }

    
}
