package api;

import api.conexao.CandidatoDAO;
import api.conexao.DTO.Candidato;
import api.conexao.DTO.Experiecia_Profissional;
import api.conexao.DTO.Experiencia_Academica;
import javax.swing.JOptionPane;
/**
 *
 * @author Lucas Emanoel
 */
public class CadastroCand extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCand
     */
    public CadastroCand() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        txtsenha = new javax.swing.JPasswordField();
        txtconfirma = new javax.swing.JPasswordField();
        txtsalario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtformacao_academica = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtexperiencia_profissional = new javax.swing.JTextArea();
        txtnaopossuiacd = new javax.swing.JRadioButton();
        txtnaopossuiprof = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        txtdata = new javax.swing.JFormattedTextField();
        txtcpf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(243, 84, 22));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salvar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 230, 30));
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 360, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 360, -1));
        getContentPane().add(txttelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 360, -1));
        getContentPane().add(txtendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 360, -1));
        getContentPane().add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 360, -1));
        getContentPane().add(txtconfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 360, -1));
        getContentPane().add(txtsalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 360, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(243, 84, 22));
        jLabel12.setText("CPF");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(243, 84, 22));
        jLabel13.setText("Nome Completo");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(243, 84, 22));
        jLabel14.setText("Email");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(243, 84, 22));
        jLabel15.setText("Telefone");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel16.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(243, 84, 22));
        jLabel16.setText("Endereço");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel17.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(243, 84, 22));
        jLabel17.setText("Data de Nascimento");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel18.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(243, 84, 22));
        jLabel18.setText("Senha");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel19.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(243, 84, 22));
        jLabel19.setText("Confirme Senha");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(243, 84, 22));
        jLabel11.setText("Cargo de Interesse");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        jLabel20.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(243, 84, 22));
        jLabel20.setText("Pretensão Salarial");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        txtformacao_academica.setColumns(20);
        txtformacao_academica.setRows(5);
        jScrollPane1.setViewportView(txtformacao_academica);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 410, -1));

        jLabel21.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(243, 84, 22));
        jLabel21.setText("Formação Acadêmica");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        txtexperiencia_profissional.setColumns(20);
        txtexperiencia_profissional.setRows(5);
        jScrollPane2.setViewportView(txtexperiencia_profissional);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 380, -1));

        txtnaopossuiacd.setText("Não Possuo");
        getContentPane().add(txtnaopossuiacd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        txtnaopossuiprof.setText("Não Possuo");
        getContentPane().add(txtnaopossuiprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        jLabel22.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(243, 84, 22));
        jLabel22.setText("Experiencia Profissional");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco de Dados", "Full Stack", "FrontEnd", "BackEnd", "Machine Learning" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco de Dados", "Full Stack", "FrontEnd", "BackEnd", "Machine Learning" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco de Dados", "Full Stack", "FrontEnd", "BackEnd", "Machine Learning" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, -1));

        try {
            txtdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 360, -1));

        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 360, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/api/Images/candidato-cadastro2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        long telefone ;
        double salario;
        String nome, data, email, CPF, endereco, senha, confirma, formacaoAcademica, formacaoProfissional, naopossuiAcd, naopossuiProf;
        
        Candidato objcandidato = new Candidato();
        Experiencia_Academica objexacd = new Experiencia_Academica();
        Experiecia_Profissional objexprof= new Experiecia_Profissional();
        
        CPF = txtcpf.getText();
        nome = txtnome.getText();
        data = txtdata.getText();
        email = txtemail.getText();
        endereco = txtendereco.getText();
        telefone = Long.parseLong(txttelefone.getText());
        salario = Double.parseDouble(txtsalario.getText());
        senha = txtsenha.getText();
        confirma = txtconfirma.getText();
        formacaoAcademica = txtformacao_academica.getText();
        formacaoProfissional = txtexperiencia_profissional.getText();
        naopossuiAcd = txtnaopossuiacd.getText();
        naopossuiProf = txtnaopossuiprof.getText();
        
        
        objcandidato.setCPF(CPF);
        objcandidato.setNome_Completo(nome);
        objcandidato.setData_Nascimento(data);
        objcandidato.setEmail(email);
        objcandidato.setEndereco(endereco);
        objcandidato.setTelefone(telefone);
        objcandidato.setSalario(salario);
        objcandidato.setSenha(senha);
        objcandidato.setConfirma(confirma);

        
        if (naopossuiAcd.equals("") && naopossuiProf.equals("")) {
            objexprof.setDescricao("Nao possui experiencia profissional");
            objexacd.setDescricao("Nao possui formacao academica");
           
        } else if (naopossuiProf.equals("")){
            objexprof.setDescricao("Nao possui experiencia profissional");
            
        } else if (naopossuiAcd.equals("")){
           objexacd.setDescricao("Nao possui experiencia academica");
           
        } else{
            objexacd.setDescricao(formacaoAcademica);
            objexprof.setDescricao(formacaoProfissional);
        }
        CandidatoDAO objcandidatodao = new CandidatoDAO();
        
        if (senha.equals(confirma)){

            objcandidatodao.cadastrarCandidato(objcandidato);
            objcandidatodao.cadastrarexperiencias(objexacd, objcandidato, objexprof);

        } else {
            
            JOptionPane.showMessageDialog(null, "As senhas nao sao as mesmas");
        }
        
        
        
                
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPasswordField txtconfirma;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JFormattedTextField txtdata;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextArea txtexperiencia_profissional;
    private javax.swing.JTextArea txtformacao_academica;
    private javax.swing.JRadioButton txtnaopossuiacd;
    private javax.swing.JRadioButton txtnaopossuiprof;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtsalario;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration                   
}
